### ISSUE TITLE
usb-rom-service not working

### ISSUE THREAD

**Issue by Renetrox** [V0rt3x667/ArchyPie-Setup#11]
tested on manjaro arm, orangepi 3lts. The binary required to boot roms from usb cannot be installed.

**Comment by V0rt3x667** [comment]
Hi, thanks for trying the script. I will look into this issue.

**Comment by V0rt3x667** [comment]
Hi, I have fixed the usbromservice via commit: c92664712c3818de00a879c0dfe172fecc191d53. You will need to create a folder called archypie-mount on your usb drive. If you are running a desktop environment you must ensure it is not set to auto-mount usb drives or the script will not work. Thanks.

**Comment by Renetrox** [comment]
> Hola, arreglé el usbromservice a través de commit: [c926647](https://github.com/V0rt3x667/ArchyPie-Setup/commit/c92664712c3818de00a879c0dfe172fecc191d53) . Deberá crear una carpeta llamada archypie-mount en su unidad USB. Si está ejecutando un entorno de escritorio, debe asegurarse de que no esté configurado para montar unidades USB automáticamente o el script no funcionará. Gracias.

 Thank you my dear friend, for your time and effort!  I was trying to make a retro console with orange pi 3 lts. I invite you to the Telegram group: t.me/rearmit . If you like to participate, it is an enterprise based on retropie and batocera for arm boards

**Comment by V0rt3x667** [comment]
Your welcome. Thanks for the invite I will check it out.

**Comment by V0rt3x667** [comment]
Issue appears to fixed. Closing for now.
