### ISSUE TITLE
Installation Errors with b-em and mupen64plus

### ISSUE THREAD

**Issue by scorpion81** [V0rt3x667/ArchyPie-Setup#2]
Hello,

I encountered a few issues so far when attempting to run the setup script on manjaro linux.

First, something seems to be wrong with acquiring the mupen64plus sources (wrong repo url ?)

```
= = = = = = = = = = = = = = = = = = = = =
Getting sources for 'mupen64plus' : MUPEN64Plus - Nintendo N64 Emulator
= = = = = = = = = = = = = = = = = = = = =

git clone --recursive --branch mupen64plus-core "https://github.com/mupen64plus" "/home/martin/Projekte/archypie/ArchyPie-Setup/tmp/build/mupen64plus/"
Klone nach '/home/martin/Projekte/archypie/ArchyPie-Setup/tmp/build/mupen64plus'...
remote: Not Found
fatal: Repository 'https://github.com/mupen64plus/' nicht gefunden 
```

Then, there is another error with installing the b-em emulator.

```
Could not successfully install B-em - Acorn BBC Micro A, B, B+, Master 128, 512, Compact & Turbo Emulator (/home/martin/Projekte/archypie/ArchyPie-Setup/tmp/build/b-em/allegro-5/lib not found).
```
Here is the full log: 
[rps_2022-06-06_105859.log.gz](https://github.com/V0rt3x667/ArchyPie-Setup/files/8843678/rps_2022-06-06_105859.log.gz)

**Comment by V0rt3x667** [comment]
Thank you for trying out the script and reporting the errors. I am in the process of reviewing and testing the modules. I will look into these two asap.

**Comment by V0rt3x667** [comment]
Hi, could you please update the script and test again? Thank you.

**Comment by scorpion81** [comment]
Hello,
I updated the script and now those two emulators install without problems :+1: Thanks for looking into it :slightly_smiling_face:
