### ISSUE TITLE
Error build core fs-uae and duckstation

### ISSUE THREAD

**Issue by chrisripp** [V0rt3x667/ArchyPie-Setup#21]
Hello I use Manjaro, and I've 2 builds errors. Emulator Duckstation build error. And puae core error with capsimg not found. I've copy/past my capsimg when the compil Begin, like it the compil work good. Puae2021 ok no probleme, just puae.
I hav'nt ES.desktop or Archypie.fesktop. I've create a .desktop in my home/local/share/applications. And it's good.

**Comment by V0rt3x667** [comment]
Hi thanks for checking out the script and reporting the bugs. I will take a look at the issues.

**Comment by chrisripp** [comment]
thank you.

**Comment by V0rt3x667** [comment]
Hello, I have updated DuckStation, PUAE and PUAE2021 and they now work. The ArchyPie shortcut is created in /usr/share/applications. If you have any further issues please let me know. Thanks

**Comment by chrisripp** [comment]
Very Nice, I'll will testing this week. Have a Nice day

Le jeu. 26 janv. 2023 à 23:09, V0rt3x667 ***@***.***> a
écrit :

**Comment by V0rt3x667** [comment]
Closing for now. Can be reopened if there are any further issues.
