### ISSUE TITLE
emulationstation.sh interferes with Skyscraper check

### ISSUE THREAD

**Issue by Subtixx** [V0rt3x667/ArchyPie-Setup#28]
One cannot run [this](https://github.com/V0rt3x667/ArchyPie-Setup/blob/52256736f2841af579f86a78b29ecbaf2e2bb39b/scriptmodules/supplementary/emulationstation.sh) script in conjunction with skyscraper. Since the check here https://github.com/V0rt3x667/ArchyPie-Setup/blob/52256736f2841af579f86a78b29ecbaf2e2bb39b/scriptmodules/supplementary/skyscraper.sh#L470-L474 will result in catching the shell script.

Personally this is a huge problem since I want to install all themes + scrap all game data, without modifying the code I cannot do this currently :/

**Comment by V0rt3x667** [comment]
Yes this does present an issue if booting straight into EmulationStation then going to the ArchyPie menu and then selecting ArchyPie Setup in order to configure themes and meta data. I don't think upstream have put a solution in place but I could be wrong. I will look into this. Thanks for letting me know.

**Comment by V0rt3x667** [comment]
Look into alternative frontends such as EmulationStation-DE or Pegasus-FE. Recalbox\Batocera have their own versions of ES as well.

**Comment by TrazhCant** [comment]
I have been able to scrape images within ES from TheGamesDB and ScreenScraper.  I enabled Videos in the config, but no matter what the videos are not scraping.  If I try to do scraping via the ArchyPie-Setup script, it says I need to update SkyScraper.  But when I back out to the main script menu and try to update that module specifically, it says it's already up to date.

**Comment by V0rt3x667** [comment]
The version Skyscraper used should be 3.9.1. Could you please remove and reinstall Skyscraper? Regarding scraping videos from EmulationStation which system are you trying to scrape for? Thanks

**Comment by TrazhCant** [comment]
Ok I'll do that as soon as I can get home in a while. I am trying to scrape video for Sega 32x

**Comment by TrazhCant** [comment]
I removed SkyScraper, updated the ArchyPie script, reinstalled SkyScraper and still had the same result.  Here's some screenshots:

![Screenshot from 2023-10-29 20-02-05](https://github.com/V0rt3x667/ArchyPie-Setup/assets/69919729/8306006e-bb36-4b2f-8144-725f9b2fb3e7)
![Screenshot from 2023-10-29 20-02-29](https://github.com/V0rt3x667/ArchyPie-Setup/assets/69919729/23eb0995-ab03-411f-a661-d4c0b69b1bf3)
![Screenshot from 2023-10-29 20-03-09](https://github.com/V0rt3x667/ArchyPie-Setup/assets/69919729/001f124e-8a70-45cc-8625-5d783af17565)

**Comment by V0rt3x667** [comment]
I have disabled version checking in the Skyscraper script for now. If you could update the script Skyscraper should work again. I don't think the scraper in EmulationStation downloads videos and as far as I know there is no option to change this.

**Comment by TrazhCant** [comment]
I am now able to scrape images and videos using the setup script to run skyscraper.  Thanks much! :)

**Comment by V0rt3x667** [comment]
I can't do anything to change how EmulationStation will overwrite changes to gamelists when it is open.
