### ISSUE TITLE
asplashscreen.sh uses old RetroPie path

### ISSUE THREAD

**Issue by Subtixx** [V0rt3x667/ArchyPie-Setup#29]
https://github.com/V0rt3x667/ArchyPie-Setup/blob/52256736f2841af579f86a78b29ecbaf2e2bb39b/scriptmodules/supplementary/splashscreen/asplashscreen.sh#L9

**Comment by V0rt3x667** [comment]
I am going to remove this module for now. It is too specific to RetroPie (the name and logo are copyrighted) and it is intended for Raspberry Pis only. When I get around to designing a logo, I will revisit this module and make it usable on all platforms.
