### ISSUE TITLE
retroach error compile

### ISSUE THREAD

**Issue by aka0kuro** [V0rt3x667/ArchyPie-Setup#3]
Hello, I get error when compiling retroarch, this is the error it gives me
`gfx/drivers_context/vc_egl_ctx.c: En la función ‘gfx_ctx_vc_has_focus’:
gfx/drivers_context/vc_egl_ctx.c:485:69: aviso: el control alcanza el final de una función que no es void [-Wreturn-type]
  485 | static bool gfx_ctx_vc_has_focus(void *data) { return g_egl_inited; }
      |                                                                     ^
make: *** [Makefile:206: obj-unix/release/gfx/drivers_context/vc_egl_ctx.o] Error 1
make: *** Se espera a que terminen otras tareas....
`
Use manjaro minimal in raspberry pi 4 of 4gb

**Comment by V0rt3x667** [comment]
Hi, unfortunately I only have a raspberry pi 2 to test on. I don't think the Manjaro Arm version works on anything less than an rpi4. I will try to replicate the issue on my rpi2 with Arch Linux Arm and get back to you. Are you compiling directly on the rpi4 or using DistCC to cross compile? Thanks

**Comment by aka0kuro** [comment]
Hi, e managed to install the retroach in raspberry pi 4 aarch4 minimal manjaro the command that failed was l.
`./configure  --disable-videocore --disable-opengl1 --enable-kms --disable-x11 --enable-opengles --enable-opengles3 --enable-opengl_core`
would be good if you can add an option of raspberry pi4 to the script. I can test

**Comment by V0rt3x667** [comment]
Hi, I have made some changes to the script. You will need to update the script either from the archypie menu or by doing a git pull.

**Comment by V0rt3x667** [comment]
Commit a75e202dc4e9de835eded8d75bbdf119b132831d fixes the issue with the wrong rpi flags being set.
