### ISSUE TITLE
cemu

### ISSUE THREAD

**Issue by KP2048** [V0rt3x667/ArchyPie-Setup#30]
cemu has a native linux version now, could this be added in the future?

**Comment by V0rt3x667** [comment]
Hi, thanks for letting me know. I will try and get this added by the end of the week.

**Comment by KP2048** [comment]
Thanks

**Comment by V0rt3x667** [comment]
I have added Cemu. Any issues please let me know.

**Comment by KP2048** [comment]
Please add .wua to list of extensions for wiiu

**Comment by V0rt3x667** [comment]
I have now added the extension.

**Comment by V0rt3x667** [comment]
Closing as completed.
