### ISSUE TITLE
Manjaro Basic install takes hours

### ISSUE THREAD

**Issue by BGPhilbin** [V0rt3x667/ArchyPie-Setup#31]
I followed this installation to the letter and, after choosing the "Basic" installation option - a few hours later, it's still at compiling the MAME portion. Is this normal?

**Comment by V0rt3x667** [comment]
Hi, MAME takes a long time to compile on all platforms, however on a Raspberry Pi I have heard people mention that it can take a whole day to build! The more CPU cores you have the quicker the compilation.

**Comment by BGPhilbin** [comment]
Good to know - thank you!

**Comment by V0rt3x667** [comment]
Closing as completed.
