### ISSUE TITLE
Updating glslang 11.13.0-2 to 12.x causes RetroArch launch error

### ISSUE THREAD

**Issue by TrazhCant** [V0rt3x667/ArchyPie-Setup#32]
Update to glslang broke RetroArch launch

Description
Updating glslang 11.13.0-2 to 12.x causes RetroArch launch error:

retroarch: error while loading shared libraries: libglslang.so.11: cannot open shared object file: No such file or directory

Expected behavior
successful RetroArch launch

Actual behavior
RetroArch fails to launch with error message:

retroarch: error while loading shared libraries: libglslang.so.11: cannot open shared object file: No such file or directory

Steps to reproduce the bug
Update glslang from 11.13.0-2 to 12.1.0-1
Attempt launch RetroArch
Bisect Results
Experienced issue today. glslang update build date is 3/22/2023.

Version/Commit
RetroArch: [version/commit] 1.14.0/ad89b0c655fc1d25adfcdf40268e95c5d0391111
Environment information
OS: EndeavourOS + Gnome43 w/ Wayland

Downgraded glslang to 11.13.0-2 using Downgrade command in EndeavourOS.  RetroArch 1.15 is available as of last week and may be patched (haven't tested it myself as glslang downgrade is sufficient for me for now)

**Comment by V0rt3x667** [comment]
Hi, thanks for reporting the issue. This a problem that occurs on rolling release distros. When a library is updated all software that links against a previous version of that library has to be rebuilt to link against the current version.

I would advise you to keep your system on the latest updates and rebuild RetroArch against the latest version of glslang.

**Comment by TrazhCant** [comment]
How do I rebuilt RetroArch to the latest version with the ArchyPie script?

**Comment by V0rt3x667** [comment]
It won't be  to the latest version just 1.14. To do that you need to go to manage packages - core packages - retroarch and the reinstall from source.

**Comment by TrazhCant** [comment]
I am on RetroArch 1.14.  RetroArch 1.15 came out last week.  The glslang update (12.x) breaks RetroArch 1.14.  So I had to revert glslang from 12.x to 11.13.0-2 because the ArchyPie script doesn't update RetroArch past 1.14 (RetroArch 1.15 just came out last week, you haven't had time to deal with that yet I'm sure, which is why ArchyPie still only updates to RetroArch 1.14 presently).

Am I making sense?  Or am I REEEEEALLY confused and lost? lol I'll have to defer to your judgement.  I'm an idiot just mashing buttons to run whatever script I can get my hands on, it seems like lol

**Comment by V0rt3x667** [comment]
RetroArch should have no problems building against glslang 12. I will test and get back to you.

**Comment by TrazhCant** [comment]
> RetroArch should have no problems building against glslang 12. I will test and get back to you.

Yes it will build.  It will not Launch.  ;)

**Comment by V0rt3x667** [comment]
Just rebuilt against glslang 12.1.0 and it works fine. Are you getting any error messages? If you go to /dev/shm/ there are two run command log files there.

**Comment by TrazhCant** [comment]
![Screenshot from 2023-03-23 10-27-23](https://user-images.githubusercontent.com/69919729/227595317-4dcc3eb6-2fb2-450c-863f-76051372e946.png)

**Comment by TrazhCant** [comment]
So if I'm understanding that error correctly, so.11 doesn't exist.  When I rolled glslang back to 11.13.0-2 it existed and I no longer received the error.

**Comment by V0rt3x667** [comment]
Hi, yes in a nutshell that is the issue. The dynamic library no longer exists and RetroArch throws the error. In the Windows world it would be the equivalent of a missing dll file.

**Comment by V0rt3x667** [comment]
Hi, I have updated RetroArch to v1.15.0. Please note that have not included the patch that changes RetroArch's save path to the ArchyPie roms folder. I want to keep the roms folder free of unnecessary files. RetroArch's default save path is ${HOME}/.config/retroarch/saves. Any issues please let me know.

**Comment by TrazhCant** [comment]
Awesome, thank you much! :)

-Mitchell-
