### ISSUE TITLE
PCSX2 is failing at patching 

### ISSUE THREAD

**Issue by mafiaphreak** [V0rt3x667/ArchyPie-Setup#33]
I am running it as it says on the github. I have tried a few different distros it fails everytime at this point pcsx2 patch /home/test/Desktop/ArchyPie-Setup/scriptmodules/emulators/pcsx2/01_set_default_config_path.patch failed to apply
Yes i know it was done in a VM, when i tried manjaro,archlab or reborn it all fails at this step. 
[rps_2023-06-30_015617.log](https://github.com/V0rt3x667/ArchyPie-Setup/files/11913798/rps_2023-06-30_015617.log)

**Comment by V0rt3x667** [comment]
Hi, thanks for trying out the script and reporting the bug. I have added commit 1202c2d which fixes this issue.  You will need to update the ArchyPie script and the run the pcsx2 module again.

Any issues please let me know. Thanks.

**Comment by mafiaphreak** [comment]
I had to pacman -S libzip for some reason the first time it failed to compile it with the new changes says it was missing when compiling. After doing that it compiled and patched just fine. Not sure if libzip was on my end or the scripts end. It works now 
distro was Endeavouros

**Comment by V0rt3x667** [comment]
Thanks for letting me know, I have now added libzip to the pcsx2 dependencies.

**Comment by TrazhCant** [comment]
This will not install.  EndeavourOS.

**Comment by TrazhCant** [comment]
```
Submodule path '3rdparty/xz/xz': checked out '3d566cd519017eee1a400e7961ff14058dfaf33c'
From https://github.com/facebook/zstd
 * branch            63779c798237346c2b245c546c40b72a5a5913fe -> FETCH_HEAD
Submodule path '3rdparty/zstd/zstd': checked out '63779c798237346c2b245c546c40b72a5a5913fe'
HEAD is now in branch 'master' at commit 'bb7e08cdce1de6265978304d9ecf7d5136641101'
patching file pcsx2/Pcsx2Config.cpp
Hunk #1 FAILED at 1601.
1 out of 1 hunk FAILED -- saving rejects to file pcsx2/Pcsx2Config.cpp.rej
x .github/
x .github/workflows/
x .github/workflows/check.yml
x LICENSE
x README.md
x duplicates.py
x gamecontrollerdb.txt
x mapping_guide.png
pcsx2 patch /home/nutzhell/ArchyPie-Setup/scriptmodules/emulators/pcsx2/01_set_default_config_path.patch failed to apply
```

**Comment by V0rt3x667** [comment]
Thanks for reporting this. I will get the patch updated.

**Comment by V0rt3x667** [comment]
I have updated the patch and build script. Could you please test again? Thanks
