### ISSUE TITLE
Unable to install binary for joy2key

### ISSUE THREAD

**Issue by TrazhCant** [V0rt3x667/ArchyPie-Setup#34]
Running EndeavourOS with Gnome/Wayland.  Fresh install.  I can't determine any details from this log other than "unable to install".  I tried manually installing joy2key using yay and still got the same error.  Does joy2key's code need patched maybe?

```
= = = = = = = = = = = = = = = = = = = = =
Installing (Binary) 'joy2key' : Provides Joystick To Keyboard Conversion For Navigation Of ArchyPie Dialog Menus
= = = = = = = = = = = = = = = = = = = = =

Compiling '/opt/archypie/admin/joy2key/joy2key.py'...
Compiling '/opt/archypie/admin/joy2key/joy2key_sdl.py'...
Compiling '/opt/archypie/admin/joy2key/osk.py'...
Unable to install binary for joy2key

Log Ended At: Thu Oct 26 06:15:54 PM PDT 2023
Total Running Time: 0 hours, 0 mins, 18 secs
```

**Comment by V0rt3x667** [comment]
Hi, sorry I have not had chance to investigate yet. I will look into the issue today.

**Comment by V0rt3x667** [comment]
It appears to build and run fine on my Arch Linux machine. I will have to create a test EndeavourOS VM to test further.

**Comment by V0rt3x667** [comment]
Hi, I discovered what the issues were. I have updated the script, could you please update the script from the setup menu and test for me? Thank you.

**Comment by TrazhCant** [comment]
It is now successful.  Thanks! :)
