### ISSUE TITLE
SNES9X Failed to patch 

### ISSUE THREAD

**Issue by mafiaphreak** [V0rt3x667/ArchyPie-Setup#35]
Reborn OS fully updated

Log Started At: Wed Nov 15 02:32:17 PM CST 2023

ArchyPie-Setup Version: 4.9.0_beta (faf5c7c)
System: x86_64 (x86_64) - RebornOS "RebornOS Linux" rolling - Linux test-virtualbox 6.6.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 08 Nov 2023 16:05:38 +0000 x86_64 GNU/Linux

= = = = = = = = = = = = = = = = = = = = =
Installing Dependencies For: 'snes9x' : SNES9X: Nintendo SNES Emulator
= = = = = = = = = = = = = = = = = = = = =

/home/test/ArchyPie-Setup/tmp/build/snes9x /home/test/ArchyPie-Setup

= = = = = = = = = = = = = = = = = = = = =
Getting Sources For 'snes9x' : SNES9X: Nintendo SNES Emulator
= = = = = = = = = = = = = = = = = = = = =

git clone --recursive --depth 1 --shallow-submodules --branch 1.62.3 "https://github.com/snes9xgit/snes9x" "/home/test/ArchyPie-Setup/tmp/build/snes9x"
Cloning into '/home/test/ArchyPie-Setup/tmp/build/snes9x'...
Note: switching to '8b82d487937d9ea39f7229d280c6f6686c415fe7'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Submodule 'shaders/SPIRV-Cross' (https://github.com/KhronosGroup/SPIRV-Cross.git) registered for path 'external/SPIRV-Cross'
Submodule 'shaders/glslang' (https://github.com/KhronosGroup/glslang.git) registered for path 'external/glslang'
Submodule 'external/vulkan-headers' (https://github.com/KhronosGroup/Vulkan-Headers.git) registered for path 'external/vulkan-headers'
Submodule 'win32/libpng/src' (https://git.code.sf.net/p/libpng/code) registered for path 'win32/libpng/src'
Submodule 'win32/zlib/src' (https://github.com/madler/zlib.git) registered for path 'win32/zlib/src'
Cloning into '/home/test/ArchyPie-Setup/tmp/build/snes9x/external/SPIRV-Cross'...
Cloning into '/home/test/ArchyPie-Setup/tmp/build/snes9x/external/glslang'...
Cloning into '/home/test/ArchyPie-Setup/tmp/build/snes9x/external/vulkan-headers'...
Cloning into '/home/test/ArchyPie-Setup/tmp/build/snes9x/win32/libpng/src'...
Cloning into '/home/test/ArchyPie-Setup/tmp/build/snes9x/win32/zlib/src'...
From https://github.com/KhronosGroup/SPIRV-Cross
 * branch            4e2fdb25671c742a9fbe93a6034eb1542244c7e1 -> FETCH_HEAD
Submodule path 'external/SPIRV-Cross': checked out '4e2fdb25671c742a9fbe93a6034eb1542244c7e1'
From https://github.com/KhronosGroup/glslang
 * branch            6d41bb9c557c5a0eec61ffba1f775dc5f717a8f7 -> FETCH_HEAD
Submodule path 'external/glslang': checked out '6d41bb9c557c5a0eec61ffba1f775dc5f717a8f7'
From https://github.com/KhronosGroup/Vulkan-Headers
 * branch            a3dd2655a3a68c2a67c55a0f8b77dcb8b166ada2 -> FETCH_HEAD
Submodule path 'external/vulkan-headers': checked out 'a3dd2655a3a68c2a67c55a0f8b77dcb8b166ada2'
From https://git.code.sf.net/p/libpng/code
 * branch            b78804f9a2568b270ebd30eca954ef7447ba92f7 -> FETCH_HEAD
Submodule path 'win32/libpng/src': checked out 'b78804f9a2568b270ebd30eca954ef7447ba92f7'
From https://github.com/madler/zlib
 * branch            cacf7f1d4e3d44d871b605da3b647f07d718623f -> FETCH_HEAD
Submodule path 'win32/zlib/src': checked out 'cacf7f1d4e3d44d871b605da3b647f07d718623f'
HEAD is now in branch 'HEAD' at commit '8b82d487937d9ea39f7229d280c6f6686c415fe7'
patching file gtk/src/gtk_config.cpp
Hunk #1 FAILED at 38.
1 out of 1 hunk FAILED -- saving rejects to file gtk/src/gtk_config.cpp.rej
snes9x patch /home/test/ArchyPie-Setup/scriptmodules/emulators/snes9x/01_set_default_config_path.patch failed to apply
/home/test/ArchyPie-Setup

Log Ended At: Wed Nov 15 02:32:39 PM CST 2023
Total Running Time: 0 hours, 0 mins, 22 secs

**Comment by V0rt3x667** [comment]
Thanks for reporting the issue. I have updated the script if you could please try again. Thanks.

**Comment by mafiaphreak** [comment]
It is fixed thank you! I was able to compile it using the script

**Comment by V0rt3x667** [comment]
Your welcome.
