### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by aka0kuro** [V0rt3x667/ArchyPie-Setup#4]
Hello 
I realized that being Arch Linux does not install all the necessary packages the sript, for example base-devel is a package that in my case I do not usually install. It could be placed somewhere in the script to check all necessary packages.

**Comment by V0rt3x667** [comment]
Hi, thanks for trying the script and reporting the error. There is code in the script to check for base-devel but I will take a look as it is obviously not working.

**Comment by V0rt3x667** [comment]
Added commit 701f8d6c16d604a62fb1fdfb688238792bd62094 to fix this issue.
