### ISSUE TITLE
What to do after installation?

### ISSUE THREAD

**Issue by metapodcod** [V0rt3x667/ArchyPie-Setup#5]
I will use emulator for the first time, after installing these packages I get the error rpie command not found. I think the next steps should be documented for novice users like me. Or any tutorial video on this would be appreciated.

**Comment by V0rt3x667** [comment]
Hi, thanks for trying the script. Yeah you are correct there should be documentation but I have not got round to doing it yet. Once you have installed the Core packages: RetroArch, EmulationStation, RunCommand and ArchyPie-Menu you need to install an emulator for the system you want. Put your roms into the relevant folder in $HOME/ArchyPie and then type in emulationstation in a terminal window. You will then be asked to setup an input device, once done you should see the system listed. I hope that helps.

**Comment by Diesi-Design** [comment]
Really cool project. I'm brand new to Linux, so my feedback will unfortunately be limited. That said, ArchyPie is exactly what I am looking for. Originally I was going to run RetroPie on a VM. (I'm running Manjaro btw.) The installation appears to be a success. Currently I've only tested SNES and the issue I'm having is that the controller (i.e., original Xbox) stops working after the game loads. If anybody is interested, I'll report back on this issue should I resolve it, as well as my broader experience using ArchyPie after I've had more time to investigate.

Also, I'm looking forward to the documentation being posted! 

Thanks @V0rt3x667!

**Comment by V0rt3x667** [comment]
Hi, thanks for trying the script out and for the feedback. Regarding the controller issue, could you please tell me which SNES emulator you are using?

**Comment by LocDest** [comment]
Hi @V0rt3x667  

I'm a big advocate for using Arch based systems this passed year so thanks for this great work.

One strange issue I'm experiencing is with the ArchyPie menu within EmulationStation.
If I go to select anything in that menu the desktop will flash up, Konsole will appear, and then the setup/retroarch config appears in front of the terminal window. This is fine but I am unable to configure the RetroArch settings this way. I have no way of controlling the input via my controllers or the keyboard/mouse. Am I missing something? 

Any and all help greatly appreciated,

Doc

![Screenshot_20221222_113527](https://user-images.githubusercontent.com/19555098/209126115-90ce495a-6ea8-4e4c-a447-d9ee170382aa.png)

**Comment by V0rt3x667** [comment]
Hello, thank you for your feedback and trying out the script. When you select ArchyPie configuration from EmulationStation you should be prompted to enter your sudo password prior to seeing the menu. Do you get prompted to enter your password?

Thanks
________________________________

**Comment by V0rt3x667** [comment]
I have opened three new issues addressing the concerns raised in this ticket.
