### ISSUE TITLE
libavcodec.so.60 No such file or directory

### ISSUE THREAD

**Issue by TrazhCant** [V0rt3x667/ArchyPie-Setup#52]
When launching ANY game (in this case, arcade games using lr-mame2010), the launch fails.  Here is the log I found:

```
Parameters: 0 _SYS_ arcade /home/nutzhell/ArchyPie/roms/arcade/umk3.zip
Executing: /opt/archypie/emulators/retroarch/bin/retroarch -L /opt/archypie/libretrocores/lr-mame2010/mame2010_libretro.so --config /opt/archypie/configs/arcade/retroarch.cfg "/home/nutzhell/ArchyPie/roms/arcade/umk3.zip" --verbose --appendconfig /dev/shm/retroarch.cfg
/opt/archypie/emulators/retroarch/bin/retroarch: error while loading shared libraries: libavcodec.so.60: cannot open shared object file: No such file or directory
```

**Comment by V0rt3x667** [comment]
Hi, you will need to rebuild RetroArch as the ffmpeg library package has been updated. Only downside to using to a rolling release distro is that the moment a library is updated all the software using it has to be rebuilt against it.

**Comment by TrazhCant** [comment]
OK that worked.  (Ran setup script, went into manage packages, reinstalled).  Thanks much! :)

**Comment by V0rt3x667** [comment]
Your welcome, thanks for the update.
