### ISSUE TITLE
lr-puae2021 installation fail

### ISSUE THREAD

**Issue by Nevrdid** [V0rt3x667/ArchyPie-Setup#56]
![image](https://github.com/user-attachments/assets/8f3ee70b-baea-48b3-9330-3854dcac401d)

**Comment by V0rt3x667** [comment]
Hi, thanks for reporting the issue. I have fixed the issue, please update the script and try installing again. Thanks

**Comment by V0rt3x667** [comment]
Closing as the issue is now fixed.
